export const PAGE_CHANGED_EVENT = 'PAGE_CHANGED';
export const TOC_STATE = 'TOC_STATE';
export const ENABLE_TOC_SETTING = 'ENABLE_TOC_SETTING';
export const HIDE_Q_A_BUTTON_SETTING = 'HIDE_Q_A_BUTTON_SETTING';
export const DISABLE_AI_ON_SPACE_PRESS_SETTING = 'DISABLE_AI_ON_SPACE_PRESS_SETTING';